# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stationery by Amethyst Wang-Hoyer
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: purplewang
github_username:  jekyll

social:
  instagram: https://www.instagram.com/thingsamydrew/
  facebook: https://www.facebook.com/amethystwh
  etsy: https://www.etsy.com/shop/thingsidrew

navigation:
  - url: /portfolio/
    name: portfolio
  - url: /blog/
    name: blog
  - url: /faq/
    name: faq
  - url: https://www.etsy.com/shop/thingsidrew
    name: shop


portfolio_order:
  wedding-paper: Wedding Paper
  calligraphy: Calligraphy
  sketch-book: Sketch Book

defaults:
  - scope:
      paths: ""
    values:
      layout: default
  - scope:
      path: _posts
    values:
      categories: blog
      layout: post
  - scope:
      path: _portfolio
    values:
      layout: portfolio-entry
  - scope:
      path: _portfolio/calligraphy
    values:
      portfolioType: calligraphy
  - scope:
      path: _portfolio/wedding-paper
    values:
      portfolioType: wedding-paper
  - scope:
      path: _portfolio/sketch-book
    values:
      portfolioType: sketch-book

responsive_image_sizes:
  thumbnails:
    srcset:
      - 250
      - 500
      - 750
      - 1000
    sizes:
      - "(max-width: 500px) 460px"
      - "(max-width: 800px) 350px"
      - "215px"
  full_width:
    srcset:
      - 500
      - 800
      - 1000
      - 1600
    sizes:
      - "(max-width: 500px) 500px"
      - "800px"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: pretty

include:
  - "_pages"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - project.sublime-project
  - scripts/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/_original-images/
  - _portfolio/portfolio-template.md